platform :ios, '13.0'
target 'Onboarding_Example' do
  use_frameworks!
  supports_swift_versions '>= 4.0'
  
  pod 'Onboarding', :path => '../'

  target 'Onboarding_Tests' do
    inherit! :search_paths

    
  end
end
